apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 8080 # Port ที่ Service จะเปิดรับ
      targetPort: 80 # Port ที่ Frontend Container กำลังฟังอยู่
  type: NodePort # ทำให้เข้าถึงได้จากภายนอก
