apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
stringData:
  DATABASE_URL: "mongodb+srv://mymovielistdevsecops:4nbHyEMgZhdsYbY2@mymovielist.n00aviy.mongodb.net/mymovielist?retryWrites=true&w=majority&appName=mymovielist"